import {useState} from 'react'


import SubHeader from "../SubHeader"
import classes from './PaymentLink.module.scss'
import {AiOutlineSearch} from "react-icons/ai"
import {BiChevronDown} from "react-icons/bi"
import PaymentLinks from "./PaymentLinks"
import CreatePaymentLink from "./CreatePaymentLink"


const PaymentLinkIndex = ()=>{

    const [currentStep, setCurrentStep] = useState('')

    const handleCurrentStep = (value)=>{
            console.log(value)
            setCurrentStep(value)
    }


    return <>
    <SubHeader mainTitle="Payment Links" />
       <div className={classes['payment-link']}>
            <div  className={`${classes['sub-header']} space-between py-4`}>
                <div>
                    <h1 className="fw-500 fs-24 primary-color">All Payment links</h1>
                    <p className="fs-16 fw-400 secondary-color">This table contains all payments links generated by you</p>
                </div>
                <div>
                    <button onClick={()=>handleCurrentStep('create-payment-link-step1')}  className="btn-default fs-16" >Create new payment link</button>
                </div>
            </div>
            <div className={`${classes['search-filter']} space-between`}>
                <div className={`centralize ${classes.search}`}>
                    <input className="w-100" type="text" placeholder="search business name, payment types......" />
                    <AiOutlineSearch />
                </div>
                <div className={`centralize ${classes.filter}`}>
                    <p>filter by</p>
                    <BiChevronDown />
                </div>
            </div>
            <div>
                <PaymentLinks  />
            </div>
            <div className={`mb-5 ${classes['search-filter']} space-between`}>
                <div className={`centralize ${classes.pagination}`}>
                    <p>page 1 of 24</p>
                </div>
                <div className={`centralize ${classes.pagination}`}>
                    <p>Next</p>
                </div>
            </div>
        </div>
        <div>
            <CreatePaymentLink currentStep={currentStep} handleCurrentStep={handleCurrentStep} />
        </div>
    </>
}

export default PaymentLinkIndex